parameters:
    locale: en
    locales: [en, fr, de]

    secret: ThisTokenIsNotSoSecretChangeIt

    # a little hack to avoid errors on missing node/coffeescript.
    # remove -disabled if you want coffee.
    coffee.extension: '\.coffee-disabled$'
    coffee.bin: ''
    coffee.node: ''

    database_driver: pdo_mysql
    database_host: db
    database_port: 3306
    database_name: '%env(MYSQL_DATABASE)%'
    database_user: '%env(MYSQL_USER)%'
    database_password: '%env(MYSQL_PASSWORD)%'
    database_path: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
